baseURL = "/"
languageCode = "en-us"
title = "Hugo Lunar"

buildFuture = true
buildDrafts = false
paginate = 12

DefaultContentLanguage = "en"
pluralizelisttitles = "false"

refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = "/"

timeout = 60000

rssLimit = 3

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true



[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'onesenterprise'
    tabWidth = 4


enableInlineShortcodes = true

[permalinks]
	posts = '/:year/:month/:slugorfilename/'
  categories = '/:slug/'

[params]
	author = "Mateus Melo"
  newsletter = ""
  description = "Based on solar.lowtechmagazine solar_v2 theme"

[menu]
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  identifier = "archive"
  name = "Archive"
  url = "/archive/"
  weight = 2

[[menu.main]]
  identifier = "donate"
  name = "Donate"
  url = "/donate/"
  weight = 3

[[menu.main]]
  identifier = "articletemplatehowto"
  name = "Article Template How To"
  url = "/article-template-how-to/"
  weight = 9

defaultContentLanguage = 'en'
[languages]
	[languages.en]
    languageName = 'English'
	  weight = 1

  [languages.pt]
    languageName = 'Português'
    weight = 2

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"
  translator = "translators"
  lang = "languages"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'lang'
  weight = 80
  

