baseURL = "/"
languageCode = "en-us"
title = "LOW←TECH MAGAZINE"

buildFuture = true
buildDrafts = false
paginate = 12

DefaultContentLanguage = "en"
pluralizelisttitles = "false"

refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = "/"

timeout = 60000

rssLimit = 3

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true



[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'onesenterprise'
    tabWidth = 4


enableInlineShortcodes = true

[permalinks]
	posts = '/:year/:month/:slugorfilename/'
  categories = '/:slug/'

[params]
	author = "Kris De Decker"
  newsletter = "https://d69baa34.sibforms.com/serve/MUIEAJWIw9w82Dl4ua6FQArPaI-3Qb-zVTwPNabHQgFH51MiGF69Smy9LOC_HPoUmBj0emaXsXT87gcQXDPvtu-AZsJCHWhkkv21CdrcQu4GdnYAhZ-MrIPhwGDecagLzYxqfvkaqXg2ODcbJU4ByoDmzJK3ZTczDo2jcWtfn-En0MGKLVkgxx9TgdHqYoPabMJCMF-agLEclEwv"
  description = "This is a solar-powered website, which means it sometimes goes offline"

[menu]
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  identifier = "lowtechtitle"
  name = "Low-tech Solutions"
  url = "/low-tech-solutions/"
  weight = 2

[[menu.main]]
  identifier = "hightechtitle"
  name = "High-tech Problems"
  url = "/high-tech-problems/"
  weight = 3

[[menu.main]]
  identifier = "obsoletetitle"
  name = "Obsolete Technology"
  url = "/obsolete-technology/"
  weight = 4

[[menu.main]]
  identifier = "offline"
  name = "Offline Reading"
  url = "/offline-reading/"
  weight = 5

[[menu.main]]
  identifier = "archives"
  name = "Archive"
  url = "/archives/"
  weight = 6

[[menu.main]]
  identifier = "donate"
  name = "Donate"
  url = "/donate/"
  weight = 7

[[menu.main]]
  identifier = "ntm"
  name = "NTM"
  url = "https://www.notechmagazine.com/"
  weight = 8

defaultContentLanguage = 'en'
[languages]
	[languages.en]
    languageName = 'English'
	  weight = 1

	[languages.fr]
    languageName = 'Français'
    description = ''
	  weight = 2
	[languages.de]
    languageName = 'Deutsch'
    weight = 3
  [languages.nl]
    languageName = 'Nederlands'
    weight = 4
  [languages.es]
    languageName = 'Español'
    weight = 5
  [languages.it]
    languageName = 'Italiano'
    weight = 6
  [languages.pt]
    languageName = 'Português'
    weight = 7
  [languages.pl]
    languageName = 'Polski'
    weight = 8
  [languages.ar]
    languageName = 'العربية'
    languagedirection = 'rtl'
    weight = 9
  [languages.vn]
    languageName = 'Tiếng Việt'
    weight = 10
  [languages.ko]
    languageName = '한국어'
    weight = 11



[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"
  translator = "translators"
  lang = "languages"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'lang'
  weight = 80
  

